# Deploys IntegrationPlayground.SalesOrder.Web to the Azure App Service created by the Bicep template

name: Deploy Web
on:
  push:
    branches:
      - main
    paths:
      - 'src/IntegrationPlayground.SalesOrder.Web/**'
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 7.0.x
      - name: Build
        run: dotnet build IntegrationPlayground.SalesOrder.Web
      - name: Publish
        run: dotnet publish IntegrationPlayground.SalesOrder.Web -c Release -o ${{ github.workspace }}/publish
      - name: Deploy
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: ${{ github.workspace }}/publish

